// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login" bson:"login"`
	Register interface{} `json:"register" bson:"register"`
}

type FilterItem struct {
	Name         *string `json:"name" bson:"name"`
	Style        *string `json:"style" bson:"style"`
	Description  *string `json:"description" bson:"description"`
	Price        *int    `json:"price" bson:"price"`
	DeliveryDays *int    `json:"deliveryDays" bson:"deliveryDays"`
}

type Item struct {
	ID           string `json:"id" bson:"_id"`
	Name         string `json:"name" bson:"name"`
	Style        string `json:"style" bson:"style"`
	Description  string `json:"description" bson:"description"`
	Price        int    `json:"price" bson:"price"`
	DeliveryDays int    `json:"deliveryDays" bson:"deliveryDays"`
}

type NewItem struct {
	Name         string `json:"name" bson:"name"`
	Style        string `json:"style" bson:"style"`
	Description  string `json:"description" bson:"description"`
	Price        int    `json:"price" bson:"price"`
	DeliveryDays int    `json:"deliveryDays" bson:"deliveryDays"`
}

type NewUser struct {
	Name     string `json:"name" bson:"name"`
	Email    string `json:"email" bson:"email"`
	Password string `json:"password" bson:"password"`
}

type User struct {
	ID       string  `json:"id" bson:"_id"`
	Name     string  `json:"name" bson:"name"`
	Email    string  `json:"email" bson:"email"`
	Password *string `json:"password" bson:"password"`
}

type CredsLogin struct {
	Email    string `json:"email" bson:"email"`
	Password string `json:"password" bson:"password"`
}
